#!/usr/bin/env bash
# Download OSM tiles for a region into server/internal/web/tiles (embedded in the binary).
#
# Usage:
#   ZMIN=0 ZMAX=7 LAT=55.75 LON=37.62 SPAN=1.5 ./scripts/fetch_tiles.sh
#
# Placeholder offline tiles (z0-5) are generated by `make gentiles`;
# run this to replace them with real imagery whenever you have internet.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TILES="$ROOT/server/internal/web/tiles"

ZMIN="${ZMIN:-0}"
ZMAX="${ZMAX:-7}"
LAT="${LAT:-55.75}"          # centre latitude
LON="${LON:-37.62}"          # centre longitude
SPAN="${SPAN:-1.5}"          # approximate region size in degrees
BASE="${TILE_URL:-https://tile.openstreetmap.org}"

mkdir -p "$TILES"

tile() { # lat lon z -> "x y"
  awk -v lat="$1" -v lon="$2" -v z="$3" '
  function sec(x){ return 1/cos(x) }
  BEGIN {
    pi=3.141592653589793;
    latr=lat*pi/180;
    n=2^z;
    x=((lon+180)/360)*n;
    y=(1-log(tan(latr)+sec(latr))/pi)/2*n;
    printf "%d %d\n", int(x), int(y);
  }'
}

for z in $(seq "$ZMIN" "$ZMAX"); do
  read -r x0 y0 <<<"$(tile "$LAT" "$LON" "$z")"
  x1=$((x0 + 1)); y1=$((y0 + 1))   # crop: single tile row keeps size tiny
  echo ".. zoom $z  [$x0..$x1] x [$y0..$y1]"
  for x in $(seq "$x0" "$x1"); do
    for y in $(seq "$y0" "$y1"); do
      mkdir -p "$TILES/$z/$x"
      out="$TILES/$z/$x/$y.png"
      if [ ! -s "$out" ]; then
        curl -fsSL --retry 2 -A "privatephone/1.0 (offline map setup)" \
          "$BASE/$z/$x/$y.png" -o "$out" || rm -f "$out"
      fi
    done
  done
done

echo "done: $(find "$TILES" -name '*.png' | wc -l) tiles in $TILES"
echo "note: real OSM tiles require a network and a user-agent per their usage policy."